[project]
name = "astraecho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "easyquotation>=0.7.7",
    "flask>=3.1.2",
    "loguru>=0.7.3",
    "mcp>=1.14.1",
    "openai>=1.108.0",
    "openai-agents>=0.3.1",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
